### ISSUE TITLE
Migrating Content

### ISSUE THREAD

**Issue by Kylieg77** [silverstripe/silverstripe-userhelp-content#122]
There should be a section in the CMS User Help guide that covers how to Migrate content.  There is a tool that lets users import content using a Document  - creating Pages and Sub Pages from Headers and Sub-headers.  It exists as a CWP Module.  Users should be Prompted to either 1. View this tool in their CWP CMS, or 2.  Be Prompted to ask their developer to deploy the module.

 I believe the module is the document converter...
https://github.com/silverstripe/silverstripe-documentconverter
It is findable under help section called "other optional modules" but this is not how the Typical CMS user will want to be able to discover this feature.

**Comment by sachajudd** [comment]
Thanks @Kylieg77 ! We have added the Document converter guides to User help but unfortunately, we can't do this for all modules as there are so many, we only do this for the core modules typically. 🙂
