### ISSUE TITLE
Duplicate content block

### ISSUE THREAD

**Issue by annabayliss** [silverstripe/silverstripe-userhelp-content#140]
Hi SilverStripe team - can you advise if there will be the ability to duplicate a content block in the future?
This feature is normally housed in the editing ... button in other systems and would save time and error if blocks could be duplicated
- so that only the image and content needs to be changed (but saves having to set the styling).

Equally, if a content block could be moved from one page to another would be great (as I don't see this feature included in the v4 documentation.

Thanks Anna

**Comment by clarkepaul** [comment]
Hi, yes we would like to add these feature but it doesn't as yet have a timeframe for it. We've mocked how we would like it to function and welcome any feedback and contributions to make it happen :).

Duplicating a block https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c075839cfbaa5001082162f

Moving a block to other pages and Element areas https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5c05e4a05155fa0011591aed

**Comment by clarkepaul** [comment]
Related issues if you want to track progress...
Duplicate block https://github.com/dnadesign/silverstripe-elemental/issues/562
Move block https://github.com/dnadesign/silverstripe-elemental/issues/445
:)

**Comment by annabayliss** [comment]
Hi Paul - I think the mock-ups look great, both would be super helpful improvements 
- especially for the 'moving blocks' toast alert which gives the 'view' and 'undo' options

**Comment by sachajudd** [comment]
Hi @annabayliss, thanks for your feedback! Since there are already issues open for moving and duplicating blocks I'm going to close this one. You can following the progress of them there 🙂 In future if the features are implemented we can reopen this issue for adding v4 documentation.
