### ISSUE TITLE
More info on meta tag defaults

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-userhelp-content#150]
The information on how to use the default meta tag fields on pages is pretty light: https://userhelp.silverstripe.org/en/4/creating_pages_and_content/creating_and_editing_content/editing_content/#describing-your-content-with-metadata

We could at least include information on what meta tags will be provided by default with the framework, some information on this is captured here: https://docs.silverstripe.org/en/4/developer_guides/templates/common_variables/#meta-tags

**Comment by sachajudd** [comment]
Read my mind I was going to create this issue today 😂

**Comment by brynwhyman** [comment]
Hey @sachajudd I've added a little PR: https://github.com/silverstripe/silverstripe-userhelp-content/pull/151

Feedback is welcome!
