### ISSUE TITLE
Missing images on Session manager page

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-userhelp-content#168]
Looks like there is something up with the session manager images on this page https://userhelp.silverstripe.org/en/4/managing_your_website/session_manager/ the links are broken so assume its about how the URL was generated (seems different from the other pages).

![image](https://user-images.githubusercontent.com/555033/134086053-10a7b16e-49e3-44f8-bada-b4983121a191.png)

PR: https://github.com/silverstripe/silverstripe-userhelp-content/pull/169

**Comment by brynwhyman** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-session-manager/issues/91
