### ISSUE TITLE
SS4 User help?

### ISSUE THREAD

**Issue by andrewandante** [silverstripe/silverstripe-userhelp-content#60]
This is conspicuous by its absence - are there plans to update for 4? Is it something the community could help with?

**Comment by robbieaverill** [comment]
The `4` branch here has the userhelp content in it, we just need to add it to https://github.com/silverstripe/userhelp.silverstripe.org (and switch to major branches)

**Comment by clarkepaul** [comment]
I'm going to be doing a review in about a month to see where things are at and make appropriate changes although that is more from the CWP userhelp side first (on cwp.govt.nz) but I'm sure its going to stretch over to userhelp.

I'm sure this is something the community can help with it too :), I wouldn't know where or in what way until I get stuck in myself.

**Comment by clarkepaul** [comment]
We've made a start on updating all the guides and images to SS4, its one of main priorities now :)

**Comment by sachajudd** [comment]
User help guides for 4.x have been released! This will continue on as a work in progress. 🎉
