### ISSUE TITLE
Module userhelp issues (quicklinks)

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-userhelp-content#61]
Taxonomy:
https://github.com/silverstripe/silverstripe-taxonomy/issues/52

Asset Admin:
https://github.com/silverstripe/silverstripe-asset-admin/issues/976

**Comment by robbieaverill** [comment]
I've moved the asset-admin issue to asset-admin, the other one is closed now. Do you want to keep this open?
