### ISSUE TITLE
'Advance' the docs for advanced workflow

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-userhelp-content#63]
I find the documentation on setting up an advanced workflow could be a lot clearer.

In particular the following parts in Section 4 are confusing:
>Next, select the "Notify Publishers" action and fill out the "Notification Email". You can use several placeholders to create your email template. Set the from email, address, and subject fields. See the "Formatting Help" drop down for help.

The sample workflow only has a 'Notify users' action. Not all of the variables for the email content and headers are resolved.

>Repeat these steps for the other actions (assign and notify) but this time setting the user to the "Initiator".

This is somewhat cryptic and does not relate to the available fields.

Further, the accompanying screenshots are relevant to SS3, but confusing for users on SS4. I suggest to update them.

**Comment by clarkepaul** [comment]
We also got the same feedback with recent user research.
