### ISSUE TITLE
Add user help for tractorcow/silverstripe-fluent

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-userhelp-content#89]
Would be good if we could add some user help for https://github.com/tractorcow/silverstripe-fluent/ to replace Translatable which is now unsupported and removed from the SS4 branch of user help. We would have to add the symbolic link under the ['Optional features'](https://github.com/silverstripe/silverstripe-userhelp-content/tree/4/docs/en/03_Optional_features) section in this repo.

cc @tractorcow

**Comment by robbieaverill** [comment]
I've moved this to https://github.com/tractorcow-farm/silverstripe-fluent/issues/543
